package defpackage;

/* renamed from: bw reason: default package */
/* compiled from: PG */
public final class bw {
    public int A = -1;
    public int B = -1;
    public int C = -1;
    public int D = -1;
    public int E = -1;
    public int F = -1;
    public int G = 0;
    public int H = -1;
    public int I = -1;
    public int J = -1;
    public int K = -1;
    public int L = -1;
    public int M = -1;
    public float N = 0.0f;
    public float O = 0.0f;
    public int P = 0;
    public int Q = 0;
    public float R = 1.0f;
    public boolean S = false;
    public float T = 0.0f;
    public float U = 0.0f;
    public float V = 0.0f;
    public float W = 1.0f;
    public float X = 1.0f;
    public float Y = 0.0f;
    public float Z = 0.0f;
    public boolean a = false;
    public float aa = 0.0f;
    public float ab = 0.0f;
    public float ac = 0.0f;
    private int ad = -1;
    private int ae = -1;
    private int af = -1;
    private int ag = -1;
    private int ah = -1;
    private int ai = -1;
    public int b;
    public int c;
    public int d;
    public int e = -1;
    public int f = -1;
    public float g = -1.0f;
    public int h = -1;
    public int i = -1;
    public int j = -1;
    public int k = -1;
    public int l = -1;
    public int m = -1;
    public int n = -1;
    public int o = -1;
    public int p = -1;
    public int q = -1;
    public int r = -1;
    public int s = -1;
    public int t = -1;
    public float u = 0.5f;
    public float v = 0.5f;
    public java.lang.String w = null;
    public int x = -1;
    public int y = -1;
    public int z = -1;

    public final void a(defpackage.bu buVar) {
        buVar.d = this.h;
        buVar.e = this.i;
        buVar.f = this.j;
        buVar.g = this.k;
        buVar.h = this.l;
        buVar.i = this.m;
        buVar.j = this.n;
        buVar.k = this.o;
        buVar.l = this.p;
        buVar.m = this.q;
        buVar.n = this.r;
        buVar.o = this.s;
        buVar.p = this.t;
        buVar.leftMargin = this.A;
        buVar.rightMargin = this.B;
        buVar.topMargin = this.C;
        buVar.bottomMargin = this.D;
        buVar.u = this.M;
        buVar.v = this.L;
        buVar.w = this.u;
        buVar.x = this.v;
        buVar.y = this.w;
        buVar.J = this.x;
        buVar.K = this.y;
        buVar.A = this.N;
        buVar.z = this.O;
        buVar.C = this.Q;
        buVar.B = this.P;
        buVar.D = this.ad;
        buVar.E = this.ae;
        buVar.H = this.af;
        buVar.I = this.ag;
        buVar.F = this.ah;
        buVar.G = this.ai;
        buVar.L = this.z;
        buVar.c = this.g;
        buVar.a = this.e;
        buVar.b = this.f;
        buVar.width = this.b;
        buVar.height = this.c;
        if (android.os.Build.VERSION.SDK_INT >= 17) {
            buVar.setMarginStart(this.F);
            buVar.setMarginEnd(this.E);
        }
        buVar.a();
    }

    public final /* synthetic */ java.lang.Object clone() {
        defpackage.bw bwVar = new defpackage.bw();
        bwVar.a = this.a;
        bwVar.b = this.b;
        bwVar.c = this.c;
        bwVar.e = this.e;
        bwVar.f = this.f;
        bwVar.g = this.g;
        bwVar.h = this.h;
        bwVar.i = this.i;
        bwVar.j = this.j;
        bwVar.k = this.k;
        bwVar.l = this.l;
        bwVar.m = this.m;
        bwVar.n = this.n;
        bwVar.o = this.o;
        bwVar.p = this.p;
        bwVar.q = this.q;
        bwVar.r = this.r;
        bwVar.s = this.s;
        bwVar.t = this.t;
        bwVar.u = this.u;
        bwVar.v = this.v;
        bwVar.w = this.w;
        bwVar.x = this.x;
        bwVar.y = this.y;
        bwVar.u = this.u;
        bwVar.u = this.u;
        bwVar.u = this.u;
        bwVar.u = this.u;
        bwVar.u = this.u;
        bwVar.z = this.z;
        bwVar.A = this.A;
        bwVar.B = this.B;
        bwVar.C = this.C;
        bwVar.D = this.D;
        bwVar.E = this.E;
        bwVar.F = this.F;
        bwVar.G = this.G;
        bwVar.H = this.H;
        bwVar.I = this.I;
        bwVar.J = this.J;
        bwVar.K = this.K;
        bwVar.L = this.L;
        bwVar.M = this.M;
        bwVar.N = this.N;
        bwVar.O = this.O;
        bwVar.P = this.P;
        bwVar.Q = this.Q;
        bwVar.R = this.R;
        bwVar.S = this.S;
        bwVar.T = this.T;
        bwVar.U = this.U;
        bwVar.V = this.V;
        bwVar.W = this.W;
        bwVar.X = this.X;
        bwVar.Y = this.Y;
        bwVar.Z = this.Z;
        bwVar.aa = this.aa;
        bwVar.ab = this.ab;
        bwVar.ac = this.ac;
        bwVar.ad = this.ad;
        bwVar.ae = this.ae;
        bwVar.af = this.af;
        bwVar.ag = this.ag;
        bwVar.ah = this.ah;
        bwVar.ai = this.ai;
        return bwVar;
    }
}
