package com.google.android.gms.feedback;

/* compiled from: PG */
public class ErrorReport extends defpackage.biq implements com.google.android.gms.common.internal.ReflectedParcelable {
    public static final android.os.Parcelable.Creator CREATOR = new defpackage.bgo();
    private java.lang.String A;
    private java.lang.String B;
    private int C;
    private java.lang.String D;
    private java.lang.String E;
    private java.lang.String F;
    private java.lang.String G;
    private java.lang.String H;
    private java.lang.String[] I;
    private java.lang.String[] J;
    private java.lang.String[] K;
    private java.lang.String L;
    private java.lang.String M;
    private byte[] N;
    private int O;
    private int P;
    private int Q;
    private int R;
    private java.lang.String S;
    private java.lang.String T;
    private boolean U;
    private int V;
    private int W;
    private boolean X;
    @java.lang.Deprecated
    private java.lang.String Y;
    private java.lang.String Z;
    @android.annotation.SuppressLint({"NewApi"})
    public android.app.ApplicationErrorReport a = new android.app.ApplicationErrorReport();
    private java.lang.String aa;
    private java.lang.String[] ab;
    private java.lang.String ac;
    private boolean ad;
    private android.os.Bundle ae;
    private java.util.List af;
    public java.lang.String b;
    public java.lang.String c;
    public android.os.Bundle d;
    public java.lang.String e;
    public java.lang.String f;
    public int g;
    public java.lang.String h;
    public java.lang.String i;
    public java.lang.String j;
    public java.lang.String k;
    public java.lang.String l;
    public com.google.android.gms.common.data.BitmapTeleporter m;
    public defpackage.bgl[] n;
    public boolean o;
    public java.lang.String p;
    public defpackage.bgn q;
    public defpackage.bgm r;
    public boolean s;
    public android.graphics.Bitmap t;
    private int u;
    private java.lang.String v;
    private java.lang.String w;
    private java.lang.String x;
    private java.lang.String y;
    private java.lang.String z;

    @android.annotation.TargetApi(14)
    public ErrorReport(android.app.ApplicationErrorReport applicationErrorReport, java.lang.String str, int i2, java.lang.String str2, java.lang.String str3, java.lang.String str4, java.lang.String str5, java.lang.String str6, java.lang.String str7, java.lang.String str8, int i3, java.lang.String str9, java.lang.String str10, java.lang.String str11, java.lang.String str12, java.lang.String str13, java.lang.String[] strArr, java.lang.String[] strArr2, java.lang.String[] strArr3, java.lang.String str14, java.lang.String str15, byte[] bArr, int i4, int i5, int i6, int i7, java.lang.String str16, java.lang.String str17, java.lang.String str18, android.os.Bundle bundle, boolean z2, int i8, int i9, boolean z3, java.lang.String str19, java.lang.String str20, int i10, java.lang.String str21, java.lang.String str22, java.lang.String str23, java.lang.String str24, java.lang.String str25, java.lang.String str26, java.lang.String str27, com.google.android.gms.common.data.BitmapTeleporter bitmapTeleporter, java.lang.String str28, defpackage.bgl[] bglArr, java.lang.String[] strArr4, boolean z4, java.lang.String str29, defpackage.bgn bgn, defpackage.bgm bgm, java.lang.String str30, boolean z5, android.os.Bundle bundle2, java.util.List list, boolean z6, android.graphics.Bitmap bitmap) {
        this.a = applicationErrorReport;
        this.b = str;
        this.u = i2;
        this.v = str2;
        this.w = str3;
        this.x = str4;
        this.y = str5;
        this.z = str6;
        this.A = str7;
        this.B = str8;
        this.C = i3;
        this.D = str9;
        this.E = str10;
        this.F = str11;
        this.G = str12;
        this.H = str13;
        this.I = strArr;
        this.J = strArr2;
        this.K = strArr3;
        this.L = str14;
        this.M = str15;
        this.N = bArr;
        this.O = i4;
        this.P = i5;
        this.Q = i6;
        this.R = i7;
        this.S = str16;
        this.c = str17;
        this.T = str18;
        this.d = bundle;
        this.U = z2;
        this.V = i8;
        this.W = i9;
        this.X = z3;
        this.e = str19;
        this.f = str20;
        this.g = i10;
        this.h = str21;
        this.i = str22;
        this.j = str23;
        this.k = str24;
        this.l = str25;
        this.Y = str26;
        this.Z = str27;
        this.m = bitmapTeleporter;
        this.aa = str28;
        this.n = bglArr;
        this.ab = strArr4;
        this.o = z4;
        this.p = str29;
        this.q = bgn;
        this.r = bgm;
        this.ac = str30;
        this.ad = z5;
        this.ae = bundle2;
        this.af = list;
        this.s = z6;
        this.t = bitmap;
    }

    public ErrorReport() {
    }

    public void writeToParcel(android.os.Parcel parcel, int i2) {
        int q2 = defpackage.bjr.q(parcel, 20293);
        defpackage.bjr.a(parcel, 2, (android.os.Parcelable) this.a, i2);
        defpackage.bjr.a(parcel, 3, this.b);
        defpackage.bjr.c(parcel, 4, this.u);
        defpackage.bjr.a(parcel, 5, this.v);
        defpackage.bjr.a(parcel, 6, this.w);
        defpackage.bjr.a(parcel, 7, this.x);
        defpackage.bjr.a(parcel, 8, this.y);
        defpackage.bjr.a(parcel, 9, this.z);
        defpackage.bjr.a(parcel, 10, this.A);
        defpackage.bjr.a(parcel, 11, this.B);
        defpackage.bjr.c(parcel, 12, this.C);
        defpackage.bjr.a(parcel, 13, this.D);
        defpackage.bjr.a(parcel, 14, this.E);
        defpackage.bjr.a(parcel, 15, this.F);
        defpackage.bjr.a(parcel, 16, this.G);
        defpackage.bjr.a(parcel, 17, this.H);
        defpackage.bjr.a(parcel, 18, this.I);
        defpackage.bjr.a(parcel, 19, this.J);
        defpackage.bjr.a(parcel, 20, this.K);
        defpackage.bjr.a(parcel, 21, this.L);
        defpackage.bjr.a(parcel, 22, this.M);
        defpackage.bjr.a(parcel, 23, this.N);
        defpackage.bjr.c(parcel, 24, this.O);
        defpackage.bjr.c(parcel, 25, this.P);
        defpackage.bjr.c(parcel, 26, this.Q);
        defpackage.bjr.c(parcel, 27, this.R);
        defpackage.bjr.a(parcel, 28, this.S);
        defpackage.bjr.a(parcel, 29, this.c);
        defpackage.bjr.a(parcel, 30, this.T);
        defpackage.bjr.a(parcel, 31, this.d);
        defpackage.bjr.a(parcel, 32, this.U);
        defpackage.bjr.c(parcel, 33, this.V);
        defpackage.bjr.c(parcel, 34, this.W);
        defpackage.bjr.a(parcel, 35, this.X);
        defpackage.bjr.a(parcel, 36, this.e);
        defpackage.bjr.a(parcel, 37, this.f);
        defpackage.bjr.c(parcel, 38, this.g);
        defpackage.bjr.a(parcel, 39, this.h);
        defpackage.bjr.a(parcel, 40, this.i);
        defpackage.bjr.a(parcel, 41, this.j);
        defpackage.bjr.a(parcel, 42, this.k);
        defpackage.bjr.a(parcel, 43, this.l);
        defpackage.bjr.a(parcel, 44, this.Y);
        defpackage.bjr.a(parcel, 45, this.Z);
        defpackage.bjr.a(parcel, 46, (android.os.Parcelable) this.m, i2);
        defpackage.bjr.a(parcel, 47, this.aa);
        defpackage.bjr.a(parcel, 48, (android.os.Parcelable[]) this.n, i2);
        defpackage.bjr.a(parcel, 49, this.ab);
        defpackage.bjr.a(parcel, 50, this.o);
        defpackage.bjr.a(parcel, 51, this.p);
        defpackage.bjr.a(parcel, 52, (android.os.Parcelable) this.q, i2);
        defpackage.bjr.a(parcel, 53, (android.os.Parcelable) this.r, i2);
        defpackage.bjr.a(parcel, 54, this.ac);
        defpackage.bjr.a(parcel, 55, this.ad);
        defpackage.bjr.a(parcel, 56, this.ae);
        defpackage.bjr.b(parcel, 57, this.af);
        defpackage.bjr.a(parcel, 58, this.s);
        defpackage.bjr.a(parcel, 59, (android.os.Parcelable) this.t, i2);
        defpackage.bjr.r(parcel, q2);
    }
}
