package com.google.android.gms.feedback;

import android.annotation.SuppressLint;
import android.annotation.TargetApi;
import android.app.ApplicationErrorReport;
import android.graphics.Bitmap;
import android.os.Bundle;
import android.os.Parcel;
import android.os.Parcelable;
import com.google.android.gms.common.data.BitmapTeleporter;
import com.google.android.gms.common.internal.ReflectedParcelable;
import java.util.List;

/* compiled from: PG */
public class ErrorReport extends biq implements ReflectedParcelable {
    public static final Parcelable.Creator CREATOR = new bgo();
    private String A;
    private String B;
    private int C;
    private String D;
    private String E;
    private String F;
    private String G;
    private String H;
    private String[] I;
    private String[] J;
    private String[] K;
    private String L;
    private String M;
    private byte[] N;
    private int O;
    private int P;
    private int Q;
    private int R;
    private String S;
    private String T;
    private boolean U;
    private int V;
    private int W;
    private boolean X;
    @Deprecated
    private String Y;
    private String Z;
    @SuppressLint({"NewApi"})
    public ApplicationErrorReport a = new ApplicationErrorReport();
    private String aa;
    private String[] ab;
    private String ac;
    private boolean ad;
    private Bundle ae;
    private List af;
    public String b;
    public String c;
    public Bundle d;
    public String e;
    public String f;
    public int g;
    public String h;
    public String i;
    public String j;
    public String k;
    public String l;
    public BitmapTeleporter m;
    public bgl[] n;
    public boolean o;
    public String p;
    public bgn q;
    public bgm r;
    public boolean s;
    public Bitmap t;
    private int u;
    private String v;
    private String w;
    private String x;
    private String y;
    private String z;

    @TargetApi(14)
    public ErrorReport(ApplicationErrorReport applicationErrorReport, String str, int i2, String str2, String str3, String str4, String str5, String str6, String str7, String str8, int i3, String str9, String str10, String str11, String str12, String str13, String[] strArr, String[] strArr2, String[] strArr3, String str14, String str15, byte[] bArr, int i4, int i5, int i6, int i7, String str16, String str17, String str18, Bundle bundle, boolean z2, int i8, int i9, boolean z3, String str19, String str20, int i10, String str21, String str22, String str23, String str24, String str25, String str26, String str27, BitmapTeleporter bitmapTeleporter, String str28, bgl[] bglArr, String[] strArr4, boolean z4, String str29, bgn bgn, bgm bgm, String str30, boolean z5, Bundle bundle2, List list, boolean z6, Bitmap bitmap) {
        this.a = applicationErrorReport;
        this.b = str;
        this.u = i2;
        this.v = str2;
        this.w = str3;
        this.x = str4;
        this.y = str5;
        this.z = str6;
        this.A = str7;
        this.B = str8;
        this.C = i3;
        this.D = str9;
        this.E = str10;
        this.F = str11;
        this.G = str12;
        this.H = str13;
        this.I = strArr;
        this.J = strArr2;
        this.K = strArr3;
        this.L = str14;
        this.M = str15;
        this.N = bArr;
        this.O = i4;
        this.P = i5;
        this.Q = i6;
        this.R = i7;
        this.S = str16;
        this.c = str17;
        this.T = str18;
        this.d = bundle;
        this.U = z2;
        this.V = i8;
        this.W = i9;
        this.X = z3;
        this.e = str19;
        this.f = str20;
        this.g = i10;
        this.h = str21;
        this.i = str22;
        this.j = str23;
        this.k = str24;
        this.l = str25;
        this.Y = str26;
        this.Z = str27;
        this.m = bitmapTeleporter;
        this.aa = str28;
        this.n = bglArr;
        this.ab = strArr4;
        this.o = z4;
        this.p = str29;
        this.q = bgn;
        this.r = bgm;
        this.ac = str30;
        this.ad = z5;
        this.ae = bundle2;
        this.af = list;
        this.s = z6;
        this.t = bitmap;
    }

    public ErrorReport() {
    }

    public void writeToParcel(Parcel parcel, int i2) {
        int q2 = bjr.q(parcel, 20293);
        bjr.a(parcel, 2, this.a, i2);
        bjr.a(parcel, 3, this.b);
        bjr.c(parcel, 4, this.u);
        bjr.a(parcel, 5, this.v);
        bjr.a(parcel, 6, this.w);
        bjr.a(parcel, 7, this.x);
        bjr.a(parcel, 8, this.y);
        bjr.a(parcel, 9, this.z);
        bjr.a(parcel, 10, this.A);
        bjr.a(parcel, 11, this.B);
        bjr.c(parcel, 12, this.C);
        bjr.a(parcel, 13, this.D);
        bjr.a(parcel, 14, this.E);
        bjr.a(parcel, 15, this.F);
        bjr.a(parcel, 16, this.G);
        bjr.a(parcel, 17, this.H);
        bjr.a(parcel, 18, this.I);
        bjr.a(parcel, 19, this.J);
        bjr.a(parcel, 20, this.K);
        bjr.a(parcel, 21, this.L);
        bjr.a(parcel, 22, this.M);
        bjr.a(parcel, 23, this.N);
        bjr.c(parcel, 24, this.O);
        bjr.c(parcel, 25, this.P);
        bjr.c(parcel, 26, this.Q);
        bjr.c(parcel, 27, this.R);
        bjr.a(parcel, 28, this.S);
        bjr.a(parcel, 29, this.c);
        bjr.a(parcel, 30, this.T);
        bjr.a(parcel, 31, this.d);
        bjr.a(parcel, 32, this.U);
        bjr.c(parcel, 33, this.V);
        bjr.c(parcel, 34, this.W);
        bjr.a(parcel, 35, this.X);
        bjr.a(parcel, 36, this.e);
        bjr.a(parcel, 37, this.f);
        bjr.c(parcel, 38, this.g);
        bjr.a(parcel, 39, this.h);
        bjr.a(parcel, 40, this.i);
        bjr.a(parcel, 41, this.j);
        bjr.a(parcel, 42, this.k);
        bjr.a(parcel, 43, this.l);
        bjr.a(parcel, 44, this.Y);
        bjr.a(parcel, 45, this.Z);
        bjr.a(parcel, 46, this.m, i2);
        bjr.a(parcel, 47, this.aa);
        bjr.a(parcel, 48, this.n, i2);
        bjr.a(parcel, 49, this.ab);
        bjr.a(parcel, 50, this.o);
        bjr.a(parcel, 51, this.p);
        bjr.a(parcel, 52, this.q, i2);
        bjr.a(parcel, 53, this.r, i2);
        bjr.a(parcel, 54, this.ac);
        bjr.a(parcel, 55, this.ad);
        bjr.a(parcel, 56, this.ae);
        bjr.b(parcel, 57, this.af);
        bjr.a(parcel, 58, this.s);
        bjr.a(parcel, 59, this.t, i2);
        bjr.r(parcel, q2);
    }
}
